config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	registrations: 'users/registrations'
}

  root 'cities#index'
	get '/profile' => 'users#show'

  resources :cities do
  	resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :posts
	has_many :users, through: :posts
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, length: { in: 1..200 }
	
	belongs_to :user
	belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :cities, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @posts = City.find(params[:id]).posts
    @posts = @posts.paginate(:page => params[:page], :per_page => 10)
    @posts = @posts.order('created_at DESC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
		before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
		
  def new
  	@city = City.find(params[:city_id])
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    city = @post.city
    redirect_to city_post_path(city, @post)
  end

  def edit
  	@post = Post.find(params[:id])
    @page = "edit_post"
  end

  def update
  	@post = Post.find(params[:id])
  	@post.update(post_params)
  	redirect_to "/cities/#{@post.city.id}/posts/#{@post.id}"
  end

  def destroy
  	@post = Post.find(params[:id])
  	city = @post.city_id
  	@post.delete
  	redirect_to "/cities/#{city}"
  end

  private
  def post_params
      params
      	.require(:post).permit(:title, :content)
      	.merge(user_id: current_user.id, city_id: params[:city_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  def new
    super
  end

  #POST /resource
  def create
    super
  end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :current_city])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :current_city, :profile_pic])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = current_user
		@posts = current_user.posts
		@posts = @posts.paginate(:page => params[:page], :per_page => 10)
	end

	def edit
		@user = User.find(params[:id])
		@page = "edit_user"
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to "/profile"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% @cities.each do |city| %>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2"><%= city.name %></h1>
        <div class="row center">
          <h5 class="header col s12 light">Travel Stories</h5>
        </div>
        <div class="center">
          <button id="download-button" class="btn-large waves-effect waves-light teal lighten-1">View <%= link_to city.name, city%>'s Stories</button>
        </div>
        <br><br>
      </div>
    </div>
    <div class="parallax"><%= image_tag("#{city.photo_url}") %></div>
  </div>
<div>
<ol></ol>
</div>
<% end %>

<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light bottom-img">So many cities, so many extrodinary stories!</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><%= image_tag("atlanta.jpg") %></div>
  </div>

app/views/cities/show.html.erb
<div class="container city-show">
  <main>
      <!--Main layout-->
          <div class="row">
             <!--Main column-->
              <div class="col-lg-12">
                <h2 class="h2-responsive"><%= @city.name %></h2>
                  <!--First row-->
                  <div class="row wow fadeIn" data-wow-delay="0.4s">
                      <div class="col-md-12">
                          <!--Product-->
                          <div class="product-wrapper">

                              <!--Featured image-->
                              <div class="view overlay hm-white-light z-depth-1-half">
                                  <%= image_tag @city.photo_url, :class => "img-fluid" %>
                                  <div class="mask">
                                  </div>
                              </div>
                              <!--/.Featured image-->

                              <br>

                              <!--Product data-->

                              <hr>
                              <p><%= @city.description %></p>

                              <ul class="rating inline-ul">
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star"></i></li>
                              </ul>

                          </div>
                          <!--Product-->

                      </div>
                  </div>
                  <!--/.First row-->

                  <!--Second row-->
                  <div class="row1">

                      <!--Heading-->
                          <div class="reviews wow fadeIn" data-wow-delay="0.4s">
                              <h2 class="h2-responsive">Posts</h2>
                          </div>
                  <%= will_paginate @posts %>
                  <% @posts.each do |post| %>
                      <!--First review-->
                      <div class="reviews media wow fadeIn" data-wow-delay="0.2s">
                          <a class="media-left" href="#">
														<div class="rounded-circle">
															<%= image_tag("#{post.user.profile_pic}") %>
														</div>
                          </a>
                          <div class="media-body">
                              <h4 class="media-heading"><%= link_to "#{post.title}", city_post_path(@city, post) %></h4>
                              <post><b>Posted at:</b> <%= post.created_at.strftime ("%B %d at %I:%M %p") %></post>

                              <ul class="rating inline-ul">
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star amber-text"></i></li>
                                  <li><i class="fa fa-star"></i></li>
                                  <li><i class="fa fa-star"></i></li>
                              </ul>
                                                              <hr>
                              <div class="post-content">
                              <p> <%= post.content %></p>
                              </div>
                          </div>
                      </div>
                      <% end -%>

              <%= will_paginate @posts %>
                  </div>
                  <!--/.Second row-->
              </div>
              <!--/.Main column-->
          </div>

      <!--/.Main layout-->
  </main>
     </div>

app/views/layouts/_footer.html.erb
<!-- <footer class="page-footer teal">
  <div class="footer-copyright">
    <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <title>citi-2-citi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon1.png', sizes: '16x16 32x32' %>
    <!-- Compiled and minified CSS -->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
 -->
  <!-- Compiled and minified JavaScript -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script> -->
  <!-- CSS  -->
  <!-- <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/> -->
  </head>
  <nav class="grey lighten-4" role="navigation">
    <div class="nav-wrapper container">

<!--       <a id="logo-container" href="#" class="brand-logo" style="color: black;"><%= image_tag("logo.png", :size => "125x60") %></a>
 -->
      <div class="brand-logo"><%= link_to image_tag("logo.png", :size => "138x65"), root_path %></div>

      <ul class="right hide-on-med-and-down">
      	<% if @city %>
      		<li class="center city_name_nav"><%= @city.name %></li>
      	<% end -%>
        <% if user_signed_in? && @city %>
	        <li><%= link_to "New Post", new_city_post_path(@city) %></li>
	        <li><%= link_to "Profile", profile_path %></li>
	        <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
      	<% elsif user_signed_in? %>
      		<li><%= link_to "Profile", profile_path %></li>
      		<li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
      	<% else %>
        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
        	<li><%= link_to "Log In", new_user_session_path %></li>
        <% end -%>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><%= link_to "City to City", root_path %></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <body>

<!-- home.html -->

    <%= yield %>

<!-- home.html -->

  <footer class="page-footer teal">
    <div class="container">

    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Brandon | Charles | Jibril </a>GA WDI9 Copyright 2017
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
<h2>Edit Post</h2>
<h3><%= @post.title %></h3>

<%= form_for @post, url: {action: "update"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>
<div style="height: 170px;">

</div>
</div>

app/views/posts/new.html.erb
<div class="container">

<h2>New Post</h2>

<%= form_for [@city, @post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content, :required => true%>

  <%= f.submit :class => 'waves-effect waves-light btn' %>
<% end %>
<div style="height: 220px;">

</div>

</div>

app/views/posts/show.html.erb
<div class="container city-show">
                    <!--First row-->
                    <div class="row wow fadeIn" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
                        <div class="col-md-12">
                            <!--Product-->
                            <div class="product-wrapper">
                                <!--Featured image-->
                                <div class="view overlay hm-white-light z-depth-1-half">
                                    <%= image_tag @post.city.photo_url, :class => "img-fluid" %>
                                    <div class="mask">
                                    </div>

                                    <!-- <h3 class="price"><span class="badge red darken-2">10 $</span></h3> -->
                                </div>
                                <!--/.Featured image-->
                                <br>
                                <!--Product data-->
                                <h2 class="h2-responsive" style="display: flex;">
																	<div style="width: 100%;">
																		<%= @post.title %>
																	</div>
																<% if @post.user == current_user %>
																<div style="width: 100%;">
																	<div style="display: flex; float: right;">
																		<%= link_to 'Edit', edit_city_post_path(@post.city.id, @post), :class => "waves-effect waves-light btn" %>
																		<%= form_for @post, url: "/cities/#{@post.city.id}/posts/#{@post.id}" , method: "DELETE" do |f| %>
																		<%= f.submit "Delete", :class => "waves-effect waves-danger btn",data: { confirm: "Are you sure you want to delete #{@post.title}?"} %>
																		<% end -%>
																		<% end -%>

																	</div>

																</div>

																</h2>
                                <hr>
                                <p><%= @post.content %></p>
                                <ul class="rating inline-ul">
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                            </div>
                            <!--Product-->
                        </div>
                    </div>
                    <!--/.First row-->
                    <!--Second row-->
                    <div class="row">

                        <!--Heading-->
                            <div class="col reviews wow fadeIn" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
                                <h2 class="h2-responsive">Posted By</h2>
																<hr>
                            <!-- </div> -->

														<br>
                        <!--First review-->
                        <div class="media wow fadeIn" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
														<br>
														<a class="media-left rounded-circle" href="#">
                                <%= image_tag("#{@post.user.profile_pic}") %>
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading"><%= @post.user.first_name %> <%= @post.user.last_name %></h4>
																<hr>
																<ul class="rating inline-ul">
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
																<div >
																	<label for="">Joined:</label>
																	<p><%= @post.user.created_at || date %></p>
																	<hr>
																</div>
																<div>
																	<label for="">Current City:</label>
																	<p><%= @post.user.current_city %></p>
																	<hr>
																</div>

                                <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi cupiditate temporibus iure soluta. Quasi mollitia maxime nemo quam accusamus possimus, voluptatum expedita assumenda. Earum sit id ullam eum vel delectus!</p> -->
                            </div>
                        </div>
												</div>

                    </div>
                    <!--/.Second row-->
                </div>

app/views/static_pages/home.html.erb
<!-- <h1 style="color:blue;">City to City</h1> -->
  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
<!--         <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            </div>
            </div>
            <div class="col s12 m8">
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div> -->

        </div>
         </div>

<!-- <ol>
  <%# @cities.each do |city| %>
    <li>
      <%# link_to city.name, city%>
    </li>
  <%# end %>
</ol> -->

app/views/users/show.html.erb
<main>

        <!--Main layout-->
        <div class="container">
            <div class="row row-profile">


                <!--Sidebar-->
                <div class="col-lg-4 wow fadeIn animated" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s;">
                    <h2 class="h2-responsive">Profile Page</h2>

                    <div class="widget-wrapper">
                        <b>Name:</b> <%= @user.first_name %>
                        <%= @user.last_name %> <br />
                        <b>Current City:</b> <%= @user.current_city %> <br />
                        <b>Created At:</b> <%= @user.created_at.strftime ("%B %d, %Y at %I:%M %p") %> <br />


                       <div class="view-profile overlay hm-white-light z-depth-1-half">
                       <% if @user.profile_pic? %>
                                <%= image_tag("#{@user.profile_pic}") %>
                              <% end -%>                                    <div class="mask">
                                    </div>

                                </div>
                                </div>

                  <div>
                  <br>
                    <button class="waves-effect waves-light btn back">
                    <%= link_to "Edit Profile", edit_user_registration_path %>

                    </button>
                </div>

                </div>
                <!--/.Sidebar-->

                <!--Main column-->
                <div class="col-lg-8 hr-line">

                    <!--First row-->
                    <div class="row wow fadeIn animated" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s;">
                        <div class="col-md-12">
                            <!--Product-->
                            <div class="product-wrapper">

                                <!--Product data-->
                                <h3 class="h4-responsive">Posts</h3>
                                <hr>

                                <div class="media-body">
                                <%= will_paginate @posts %>
                                <% @posts.each do |post| %>
                        <h5 class=""><%= link_to "#{post.title}", city_post_path(post.city.id, post) %></h5>
                        <ul class="rating inline-ul">
<hr>
      <%= post.content %>  <%= link_to 'Edit', edit_city_post_path(post.city.id, post) %>
      <br>
  <br />

      <br>
  <% end -%>

<%= will_paginate @posts %>
                    </div>

                                <ul class="rating inline-ul">
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star amber-text"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>

                            </div>
                            <!--Product-->

                        </div>
                    </div>
                    <!--/.First row-->







    </main>